export const zawodnicy = [
  {
    imieNazwisko: 'Jędrasik Waldemar',
    foto: '/kadra/jedrasik.jpg',
    pozycja: 'Napastnik',
    mecze: 17,
    mecz_puchar: 2,
    gole: 36,
    gole_puchar: 2,
    asysty: 6,
    zolte: 0,
    czerwone: 0,
    dokładna_pozycja:"",
    pseudonim:"Faza"
  },
  {
    imieNazwisko: 'Dzierbun Remigiusz',
    foto: '/kadra/remik.jpg',
    pozycja: 'Pomocnik',
    mecze: 18,
    gole: 16,
    gole_puchar: 2,
    mecz_puchar: 2,
    asysty: 3,
    zolte: 2,
    czerwone: 0,
    dokładna_pozycja:"środkowy pomocnik",
    pseudonim:"Remik"
  },
  {
    imieNazwisko: 'Michalski Adrian',
    foto: '/kadra/michalski.jpg',
    pozycja: 'Pomocnik',
    mecze: 12,
    gole: 5,
    gole_puchar: 0,
    mecz_puchar: 2,
    asysty: 1,
    zolte: 7,
    czerwone: 2,
    dokładna_pozycja:"środkowy pomocnik",
    pseudonim:"animator, adi"
  },
  {
    imieNazwisko: 'Kwaśnik Maciej',
    foto: '/kadra/kwasnik.jpg',
    pozycja: 'Napastnik',
    mecze: 12,
    gole: 6,
    gole_puchar: 0,
    mecz_puchar: 0,
    asysty: 2,
    zolte: 0,
    czerwone: 0,
    dokładna_pozycja:"napastnik",
    pseudonim:"Kwaśnik"
  },
  {
    imieNazwisko: 'Agudi Edmond Ogara',
    foto: '/kadra/ogara.jpg',
    pozycja: 'Pomocnik',
    mecze: 7,
    gole: 6,
    asysty: 4,
    zolte: 0,
    czerwone: 0,
    dokładna_pozycja:"Lewy pomocnik",
    pseudonim:"EDI"
  },
  {
    imieNazwisko: 'Radziwoń Łukasz',
    foto: '/kadra/radziwon.jpg',
    pozycja: 'Pomocnik',
    mecze: 18,
    gole: 5,
    asysty: 1,
    zolte: 0,
    czerwone: 0,
    dokładna_pozycja:"prawy pomocnik",
    pseudonim:"Radzik"
  },
  {
    imieNazwisko: 'Góralczyk Damian',
    foto: '/kadra/goral.jpg',
    pozycja: 'Obrońca',
    mecze: 7,
    gole: 1,
    asysty: 1,
    zolte: 2,
    czerwone: 0,
    dokładna_pozycja:"Środkowy obrońca",
    pseudonim:"Góral"
  },
  {
    imieNazwisko: 'Bieńkowski Dawid',
    foto: '/kadra/bienkowski.jpg',
    pozycja: 'Pomocnik',
    mecze: 10,
    gole: 1,
    asysty: 1,
    zolte: 0,
    czerwone: 0,
    dokładna_pozycja:"prawy pomocnik",
    pseudonim:"Bieniu,Bienek"
  },
  {
    imieNazwisko: 'Gławdel Maciej',
    foto: '/kadra/glawdel.jpg',
    pozycja: 'Obrońca',
    mecze: 15,
    gole: 1,
    asysty: 0,
    zolte: 1,
    czerwone: 0,
    dokładna_pozycja:"lewy obrońca",
    pseudonim:"Gławdel"
  },
  {
    imieNazwisko: 'Grabek Jakub',
    foto: '/kadra/grabek.jpg',
    pozycja: 'Pomocnik',
    mecze: 6,
    gole: 1,
    asysty: 0,
    zolte: 0,
    czerwone: 0,
    dokładna_pozycja:"Pomocnik prawy,lewy",
    pseudonim:"Grabek"
  },
  {
    imieNazwisko: 'Śródecki Szymon',
    foto: '/kadra/srudecki.jpg',
    pozycja: 'Pomocnik',
    mecze: 9,
    gole: 1,
    asysty: 0,
    zolte: 0,
    czerwone: 0,
    dokładna_pozycja:"lewy pomocnik",
    pseudonim:"Szymon z parku"
  },
  {
    imieNazwisko: 'Lewandowski Janusz',
    foto: '/kadra/lewandowski.jpg',
    pozycja: 'Pomocnik',
    mecze: 15,
    gole: 1,
    asysty: 0,
    zolte: 0,
    czerwone: 0,
    dokładna_pozycja:"środkowy pomocnik",
    pseudonim:"prezes Janek"
  },
  {
    imieNazwisko: 'Paweł Czarnojan',
    foto: '/kadra/czarnojan.jpg',
    pozycja: 'Obrońca',
    mecze: 6,
    gole: 1,
    asysty: 1,
    zolte: 3,
    czerwone: 0,
    dokładna_pozycja:"prawy obrońca",
    pseudonim:"Czarny"
  },
  {
    imieNazwisko: 'Kwaśnik Michał',
    foto: '/kadra/kwasnik_mi.jpg',
    pozycja: 'Pomocnik',
    mecze: 3,
    gole: 0,
    asysty: 1,
    zolte: 0,
    czerwone: 0,
    dokładna_pozycja:"prawy pomocnik",
    pseudonim:"Kwaśnik Miachał"
  },
  {
    imieNazwisko: 'Filipowicz Szymon',
    foto: '/kadra/filipowicz.jpg',
    pozycja: 'Obrońca',
    mecze: 12,
    gole: 0,
    asysty: 0,
    zolte: 3,
    czerwone: 1,
    dokładna_pozycja:"środkowy obrońca",
    pseudonim:"Filipo"
  },
  {
    imieNazwisko: 'Skrzypiec Dominik',
    foto: '/kadra/skrzypiec.jpg',
    pozycja: 'Pomocnik',
    mecze: 14,
    gole: 0,
    asysty: 2,
    zolte: 1,
    czerwone: 0,
    dokładna_pozycja:"środkowy pomocnik",
    pseudonim:"Domino"
  },
  {
    imieNazwisko: 'Piotrowski Krzysztof',
    foto: '/kadra/piotrowski_k.jpg',
    pozycja: 'Pomocnik',
    mecze: 14,
    gole: 0,
    asysty: 2,
    zolte: 0,
    czerwone: 0,
    dokładna_pozycja:"Prawy pomocnik",
    pseudonim:"Krzysiu"
  },
  {
    imieNazwisko: 'Dzierbun Hubert',
    foto: '/kadra/dzierbun_h.jpg',
    pozycja: 'Bramkarz',
    mecze: 17,
    gole: 0,
    asysty: 0,
    zolte: 0,
    czerwone: 0,
    dokładna_pozycja:"bramkarz",
    pseudonim:"Huberto,chińczyk"
  },
  {
    imieNazwisko: 'Farbotko Krzysztof',
    foto: '/kadra/farbotko.jpg',
    pozycja: 'Obrońca',
    mecze: 15,
    gole: 0,
    asysty: 0,
    zolte: 0,
    czerwone: 0,
    dokładna_pozycja:"środkowy pomocnik",
    pseudonim:"Farbotko"
  },
  {
    imieNazwisko: 'Rembiałkowski Jakub',
    foto: '/kadra/rembialkowski.jpg',
    pozycja: 'Obrońca',
    mecze: 7,
    gole: 0,
    asysty: 0,
    zolte: 1,
    czerwone: 0,
    dokładna_pozycja:"środkowy obrońca",
    pseudonim:"biały,kuba"
  },
  {
    imieNazwisko: 'Turkosz Bartłomiej',
    foto: '/kadra/turkosz.jpg',
    pozycja: 'Obrońca',
    mecze: 11,
    gole: 0,
    asysty: 0,
    zolte: 0,
    czerwone: 0,
    dokładna_pozycja:"prawy obrońca",
    pseudonim:"Bartek"
  },
  {
    imieNazwisko: 'Wzorek Bartek',
    foto: '/kadra/wzorek.jpg',
    pozycja: 'Pomocnik',
    mecze: 10,
    gole: 0,
    asysty: 0,
    zolte: 0,
    czerwone: 0,
    dokładna_pozycja:"prawy pomocnik",
    pseudonim:"Wzorek"
  },
  {
    imieNazwisko: 'Zygała Jakub',
    foto: '/kadra/zygala.jpg',
    pozycja: 'Pomocnik',
    mecze: 0,
    gole: 0,
    asysty: 0,
    zolte: 0,
    czerwone: 0,
    dokładna_pozycja:"brak",
    pseudonim:"Kuba prezes"
  },
  {
    imieNazwisko: 'Kalinowski Kamil',
    foto: '/kadra/noname.png',
    pozycja: 'Pomocnik',
    mecze: 0,
    gole: 0,
    asysty: 0,
    zolte: 0,
    czerwone: 0,
    dokładna_pozycja:"",
    pseudonim:""
  },
  {
    imieNazwisko: 'Piotrowski Jakub',
    foto: '/kadra/noname.png',
    pozycja: 'Pomocnik',
    mecze: 5,
    gole: 0,
    asysty: 0,
    zolte: 0,
    czerwone: 0,
    dokładna_pozycja:"",
    pseudonim:""
  },
  {
    imieNazwisko: 'Domagała Mateusz',
    foto: '/kadra/noname.png',
    pozycja: 'Pomocnik',
    mecze: 3,
    gole: 0,
    asysty: 0,
    zolte: 1,
    czerwone: 0,
    dokładna_pozycja:"",
    pseudonim:""
  },
  {
    imieNazwisko: 'Mateusz Oliwier',
    foto: '/kadra/noname.png',
    pozycja: 'Pomocnik',
    mecze: 4,
    gole: 0,
    asysty: 0,
    zolte: 0,
    czerwone: 0,
    dokładna_pozycja:"",
    pseudonim:""
  },
  {
    imieNazwisko: 'Piluk Piotr',
    foto: '/kadra/noname.png',
    pozycja: 'Pomocnik',
    mecze: 3,
    gole: 0,
    asysty: 0,
    zolte: 0,
    czerwone: 0,
    dokładna_pozycja:"",
    pseudonim:""
  },
  {
    imieNazwisko: 'Rembiałkowski Radosław',
    foto: '/kadra/noname.png',
    pozycja: 'Obrońca',
    mecze: 5,
    gole: 0,
    asysty: 0,
    zolte: 0,
    czerwone: 0,
    dokładna_pozycja:"",
    pseudonim:"Radek"
  },
  {
    imieNazwisko: 'Rybak Eryk',
    foto: '/kadra/noname.png',
    pozycja: 'Bramkarz',
    mecze: 2,
    gole: 0,
    asysty: 0,
    zolte: 0,
    czerwone: 0,
    dokładna_pozycja:"",
    pseudonim:"Rybak"
  },
  {
    imieNazwisko: 'Werner Jakub',
    foto: '/kadra/noname.png',
    pozycja: 'Pomocnik',
    mecze: 1,
    gole: 0,
    asysty: 0,
    zolte: 0,
    czerwone: 0,
    dokładna_pozycja:"",
    pseudonim:""
  },
  {
    imieNazwisko: 'Zając Dawid',
    foto: '/kadra/noname.png',
    pozycja: 'Pomocnik',
    mecze: 6,
    gole: 0,
    asysty: 0,
    zolte: 0,
    czerwone: 0,
    dokładna_pozycja:"",
    pseudonim:""
  },
  {
    imieNazwisko: 'Rembiałkowski Kamil',
    foto: '/kadra/noname.png',
    pozycja: 'Trener',
    mecze: 1,
    gole: 0,
    asysty: 0,
    zolte: 0,
    czerwone: 0,
    dokładna_pozycja:"Trener",
    pseudonim:""
  },
];
