export const zawodnicy = [
  {
    imieNazwisko: 'Jędrasik Waldemar',
    foto: '/kadra/jedrasik.jpg',
    pozycja: 'Napastnik',
    mecze: 17,
    mecz_puchar: 2,
    gole: 34,
    gole_puchar: 2,
    asysty: 0,
    zolte: 0,
    czerwone: 0,
  },
  {
    imieNazwisko: 'Dzierbun Remigiusz',
    foto: '/kadra/remik.jpg',
    pozycja: 'Pomocnik',
    mecze: 18,
    gole: 16,
    gole_puchar: 2,
    mecz_puchar: 2,
    asysty: 0,
    zolte: 2,
    czerwone: 0,
  },
  {
    imieNazwisko: 'Michalski Adrian',
    foto: '/kadra/michalski.jpg',
    pozycja: 'Pomocnik',
    mecze: 12,
    gole: 5,
    gole_puchar: 0,
    mecz_puchar: 2,
    asysty: 0,
    zolte: 7,
    czerwone: 2,
  },
  {
    imieNazwisko: 'Kwaśnik Maciej',
    foto: '/kadra/kwasnik.jpg',
    pozycja: 'Napastnik',
    mecze: 12,
    gole: 6,
    gole_puchar: 0,
    mecz_puchar: 0,
    asysty: 0,
    zolte: 0,
    czerwone: 0,
  },
  {
    imieNazwisko: 'Agudi Edmond Ogara',
    foto: '/kadra/ogara.jpg',
    pozycja: 'Pomocnik',
    mecze: 7,
    gole: 5,
    asysty: 0,
    zolte: 0,
    czerwone: 0,
  },
  {
    imieNazwisko: 'Radziwoń Łukasz',
    foto: '/kadra/radziwon.jpg',
    pozycja: 'Pomocnik',
    mecze: 18,
    gole: 5,
    asysty: 0,
    zolte: 0,
    czerwone: 0,
  },
  {
    imieNazwisko: 'Góralczyk Damian',
    foto: '/kadra/goral.jpg',
    pozycja: 'Obrońca',
    mecze: 7,
    gole: 1,
    asysty: 0,
    zolte: 2,
    czerwone: 0,
  },
  {
    imieNazwisko: 'Bieńkowski Dawid',
    foto: '/kadra/bienkowski.jpg',
    pozycja: 'Pomocnik',
    mecze: 10,
    gole: 1,
    asysty: 0,
    zolte: 0,
    czerwone: 0,
  },
  {
    imieNazwisko: 'Gławdel Maciej',
    foto: '/kadra/glawdel.jpg',
    pozycja: 'Obrońca',
    mecze: 15,
    gole: 1,
    asysty: 0,
    zolte: 1,
    czerwone: 0,
  },
  {
    imieNazwisko: 'Grabek Jakub',
    foto: '/kadra/grabek.jpg',
    pozycja: 'Pomocnik',
    mecze: 6,
    gole: 1,
    asysty: 0,
    zolte: 0,
    czerwone: 0,
  },
  {
    imieNazwisko: 'Śródecki Szymon',
    foto: '/kadra/srudecki.jpg',
    pozycja: 'Pomocnik',
    mecze: 9,
    gole: 1,
    asysty: 0,
    zolte: 0,
    czerwone: 0,
  },
  {
    imieNazwisko: 'Lewandowski Janusz',
    foto: '/kadra/lewandowski.jpg',
    pozycja: 'Pomocnik',
    mecze: 15,
    gole: 1,
    asysty: 0,
    zolte: 0,
    czerwone: 0,
  },
  {
    imieNazwisko: 'Paweł Czarnojan',
    foto: '/kadra/czarnojan.jpg',
    pozycja: 'Obrońca',
    mecze: 6,
    gole: 1,
    asysty: 0,
    zolte: 0,
    czerwone: 0,
  },
  {
    imieNazwisko: 'Kwaśnik Michał',
    foto: '/kadra/kwasnik_mi.jpg',
    pozycja: 'Pomocnik',
    mecze: 3,
    gole: 0,
    asysty: 0,
    zolte: 0,
    czerwone: 0,
  },
  {
    imieNazwisko: 'Filipowicz Szymon',
    foto: '/kadra/filipowicz.jpg',
    pozycja: 'Obrońca',
    mecze: 12,
    gole: 0,
    asysty: 0,
    zolte: 2,
    czerwone: 0,
  },
  {
    imieNazwisko: 'Skrzypiec Dominik',
    foto: '/kadra/skrzypiec.jpg',
    pozycja: 'Pomocnik',
    mecze: 14,
    gole: 0,
    asysty: 0,
    zolte: 1,
    czerwone: 0,
  },
  {
    imieNazwisko: 'Piotrowski Krzysztof',
    foto: '/kadra/piotrowski_k.jpg',
    pozycja: 'Pomocnik',
    mecze: 14,
    gole: 0,
    asysty: 0,
    zolte: 0,
    czerwone: 0,
  },
  {
    imieNazwisko: 'Dzierbun Hubert',
    foto: '/kadra/dzierbun_h.jpg',
    pozycja: 'Bramkarz',
    mecze: 17,
    gole: 0,
    asysty: 0,
    zolte: 0,
    czerwone: 0,
  },
  {
    imieNazwisko: 'Farbotko Krzysztof',
    foto: '/kadra/farbotko.jpg',
    pozycja: 'Obrońca',
    mecze: 15,
    gole: 0,
    asysty: 0,
    zolte: 0,
    czerwone: 0,
  },
  {
    imieNazwisko: 'Rembiałkowski Jakub',
    foto: '/kadra/rembialkowski.jpg',
    pozycja: 'Obrońca',
    mecze: 7,
    gole: 0,
    asysty: 0,
    zolte: 1,
    czerwone: 0,
  },
  {
    imieNazwisko: 'Turkosz Bartłomiej',
    foto: '/kadra/turkosz.jpg',
    pozycja: 'Obrońca',
    mecze: 11,
    gole: 0,
    asysty: 0,
    zolte: 0,
    czerwone: 0,
  },
  {
    imieNazwisko: 'Wzorek Bartek',
    foto: '/kadra/wzorek.jpg',
    pozycja: 'Pomocnik',
    mecze: 10,
    gole: 0,
    asysty: 0,
    zolte: 0,
    czerwone: 0,
  },
  {
    imieNazwisko: 'Zygała Jakub',
    foto: '/kadra/zygala.jpg',
    pozycja: 'Pomocnik',
    mecze: 0,
    gole: 0,
    asysty: 0,
    zolte: 0,
    czerwone: 0,
  },
  {
    imieNazwisko: 'Kalinowski Kamil',
    foto: '/kadra/noname.png',
    pozycja: 'Pomocnik',
    mecze: 0,
    gole: 0,
    asysty: 0,
    zolte: 0,
    czerwone: 0,
  },
  {
    imieNazwisko: 'Piotrowski Jakub',
    foto: '/kadra/noname.png',
    pozycja: 'Pomocnik',
    mecze: 5,
    gole: 0,
    asysty: 0,
    zolte: 0,
    czerwone: 0,
  },
  {
    imieNazwisko: 'Domagała Mateusz',
    foto: '/kadra/noname.png',
    pozycja: 'Pomocnik',
    mecze: 3,
    gole: 0,
    asysty: 0,
    zolte: 1,
    czerwone: 0,
  },
  {
    imieNazwisko: 'Mateusz Oliwier',
    foto: '/kadra/noname.png',
    pozycja: 'Pomocnik',
    mecze: 4,
    gole: 0,
    asysty: 0,
    zolte: 0,
    czerwone: 0,
  },
  {
    imieNazwisko: 'Piluk Piotr',
    foto: '/kadra/noname.png',
    pozycja: 'Pomocnik',
    mecze: 3,
    gole: 0,
    asysty: 0,
    zolte: 0,
    czerwone: 0,
  },
  {
    imieNazwisko: 'Rembiałkowski Radosław',
    foto: '/kadra/noname.png',
    pozycja: 'Obrońca',
    mecze: 5,
    gole: 0,
    asysty: 0,
    zolte: 0,
    czerwone: 0,
  },
  {
    imieNazwisko: 'Rybak Eryk',
    foto: '/kadra/noname.png',
    pozycja: 'Bramkarz',
    mecze: 2,
    gole: 0,
    asysty: 0,
    zolte: 0,
    czerwone: 0,
  },
  {
    imieNazwisko: 'Werner Jakub',
    foto: '/kadra/noname.png',
    pozycja: 'Pomocnik',
    mecze: 1,
    gole: 0,
    asysty: 0,
    zolte: 0,
    czerwone: 0,
  },
  {
    imieNazwisko: 'Zając Dawid',
    foto: '/kadra/noname.png',
    pozycja: 'Pomocnik',
    mecze: 6,
    gole: 0,
    asysty: 0,
    zolte: 0,
    czerwone: 0,
  },
];
